spring:
  application:
    name: ${SPRING_APPLICATION_NAME:user-service}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/library_user_db?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    from: ${MAIL_FROM:noreply@library.com}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.amarakeerthi.userservice: DEBUG
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: ${JWT_SECRET:myVerySecureJWTSecretKeyForLibraryManagementSystem2025}
  access-token:
    expiry-ms: ${JWT_ACCESS_TOKEN_EXPIRY_MS:86400000}

# Default Admin Configuration (Optional - can override via environment variables)
app:
  admin:
    default:
      email: ${DEFAULT_ADMIN_EMAIL:admin@library.com}
      password: ${DEFAULT_ADMIN_PASSWORD:admin123456}
      fullName: ${DEFAULT_ADMIN_NAME:System Administrator}
      adminId: ${DEFAULT_ADMIN_ID:ADMIN001}
      department: ${DEFAULT_ADMIN_DEPT:IT Administration}