spring:
  application:
    name: ${SPRING_APPLICATION_NAME:late-reminders}
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/late_reminders_db?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Email Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: ${MAIL_DEBUG:false}
  
  # Quartz Scheduler Configuration
  quartz:
    job-store-type: ${QUARTZ_JOB_STORE_TYPE:memory}
    jdbc:
      initialize-schema: ${QUARTZ_INITIALIZE_SCHEMA:never}
    properties:
      org:
        quartz:
          scheduler:
            instanceName: LateRemindersScheduler
            instanceId: AUTO
          jobStore:
            class: ${QUARTZ_JOB_STORE_CLASS:org.quartz.simpl.RAMJobStore}
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5

server:
  port: ${SERVER_PORT:8085}

# Application Configuration
library-reminders:
  email:
    from: ${REMINDER_EMAIL_FROM:library-system@example.com}
    from-name: ${REMINDER_EMAIL_FROM_NAME:Library Management System}
    retry-attempts: ${EMAIL_RETRY_ATTEMPTS:3}
    retry-delay-minutes: ${EMAIL_RETRY_DELAY_MINUTES:30}
  
  scheduler:
    enabled: ${SCHEDULER_ENABLED:true}
    daily-check-time: ${DAILY_CHECK_TIME:00:00:00}
    timezone: ${SCHEDULER_TIMEZONE:UTC}
  
  services:
    borrow-service-url: ${BORROW_SERVICE_URL:http://localhost:8083}
    user-service-url: ${USER_SERVICE_URL:http://localhost:8080}

logging:
  level:
    com.kuruneru.latereminders: ${LOG_LEVEL:INFO}
    org.springframework.mail: ${MAIL_LOG_LEVEL:WARN}
    org.quartz: ${QUARTZ_LOG_LEVEL:WARN}